In [6]:
#!pip install mysql.connector
import pandas as pd

In [3]:
import mysql.connector

In [5]:
con = mysql.connector.connect(host = 'localhost', user = 'root' , password = '',database = 'world')

In [17]:
#pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND' ",con)

In [20]:
pd.read_sql_query("SELECT * FROM country WHERE Population < 10000000 ",con)

C:\Users\navee\AppData\Local\Temp\ipykernel_5788\4277865023.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM country WHERE Population < 10000000 ",con)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
2,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
3,AND,Andorra,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,,55.0,AD
4,ANT,Netherlands Antilles,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Beatrix,33.0,AN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,VIR,"Virgin Islands, U.S.",North America,Caribbean,347.0,NaN,93000,78.1,0.0,NaN,Virgin Islands of the United States,US Territory,George W. Bush,4067.0,VI
157,VUT,Vanuatu,Oceania,Melanesia,12189.0,1980.0,190000,60.6,261.0,246.0,Vanuatu,Republic,John Bani,3537.0,VU
158,WLF,Wallis and Futuna,Oceania,Polynesia,200.0,NaN,15000,NaN,0.0,NaN,Wallis-et-Futuna,Nonmetropolitan Territory of France,Jacques Chirac,3536.0,WF
159,WSM,Samoa,Oceania,Polynesia,2831.0,1962.0,180000,69.2,141.0,157.0,Samoa,Parlementary Monarchy,Malietoa Tanumafili II,3169.0,WS
160,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM